/* The contents of this file are subject to the license and copyright terms
 * detailed in the license directory at the root of the source tree (also
 * available online at http://fedora-commons.org/license/).
 */

package fedora.server.journal.readerwriter.multicast;

public class SampleJournalFile1 {

    public static final String FILE_CONTENTS =
            ""
                    + "<JournalEntry method=\"modifyDatastreamByValue\" timestamp=\"2007-02-18T08:55:07.951-0500\" clientIpAddress=\"127.0.0.1\" loginId=\"fedoraAdmin\">\n"
                    + "  <context>\n"
                    + "    <password type=\"1\">MkMwWC1dMkgxaFRROEk1RjpHN0E5RzFJ</password>\n"
                    + "    <noOp>false</noOp>\n"
                    + "    <now>2007-02-18T08:55:07.951-0500</now>\n"
                    + "    <multimap name=\"environment\">\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:authType\">\n"
                    + "        <multimapvalue>BASIC</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:security\">\n"
                    + "        <multimapvalue>urn:fedora:names:fedora:2.1:environment:httpRequest:security-secure</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:currentDate\">\n"
                    + "        <multimapvalue>2007-02-18Z</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:currentTime\">\n"
                    + "        <multimapvalue>08:55:07.951Z</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:sessionStatus\">\n"
                    + "        <multimapvalue>invalid</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:scheme\">\n"
                    + "        <multimapvalue>https</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:clientIpAddress\">\n"
                    + "        <multimapvalue>127.0.0.1</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:contentLength\">\n"
                    + "        <multimapvalue>6730</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:clientFqdn\">\n"
                    + "        <multimapvalue>repo5.nsdl.org</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:serverIpAddress\">\n"
                    + "        <multimapvalue>127.0.0.1</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:serverPort\">\n"
                    + "        <multimapvalue>8843</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:currentDateTime\">\n"
                    + "        <multimapvalue>2007-02-18T08:55:07.951Z</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:messageProtocol\">\n"
                    + "        <multimapvalue>urn:fedora:names:fedora:2.1:environment:httpRequest:messageProtocol-soap</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:contentType\">\n"
                    + "        <multimapvalue>text/xml; charset=utf-8</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:method\">\n"
                    + "        <multimapvalue>POST</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:protocol\">\n"
                    + "        <multimapvalue>HTTP/1.0</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:environment:httpRequest:serverFqdn\">\n"
                    + "        <multimapvalue>repo5.nsdl.org</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "    </multimap>\n"
                    + "    <multimap name=\"subject\">\n"
                    + "      <multimapkey name=\"fedoraRole\">\n"
                    + "        <multimapvalue>administrator</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:subject:loginId\">\n"
                    + "        <multimapvalue>fedoraAdmin</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "    </multimap>\n"
                    + "    <multimap name=\"action\"></multimap>\n"
                    + "    <multimap name=\"resource\">\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:resource:datastream:newState\">\n"
                    + "        <multimapvalue>A</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:resource:datastream:newFormatUri\">\n"
                    + "        <multimapvalue>unknown</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:resource:datastream:newMimeType\">\n"
                    + "        <multimapvalue>application/xml</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "      <multimapkey name=\"urn:fedora:names:fedora:2.1:resource:datastream:id\">\n"
                    + "        <multimapvalue>format_nsdl_dc</multimapvalue>\n"
                    + "      </multimapkey>\n"
                    + "    </multimap>\n"
                    + "    <multimap name=\"recovery\"></multimap>\n"
                    + "  </context>\n"
                    + "  <argument name=\"pid\" type=\"string\">hdl:2200%2F20061003155524381T</argument>\n"
                    + "  <argument name=\"dsId\" type=\"string\">format_nsdl_dc</argument>\n"
                    + "  <argument name=\"altIds\" type=\"stringarray\"></argument>\n"
                    + "  <argument name=\"dsLabel\" type=\"string\">format_nsdl_dc data stream</argument>\n"
                    + "  <argument name=\"versionable\" type=\"boolean\">true</argument>\n"
                    + "  <argument name=\"mimeType\" type=\"string\">application/xml</argument>\n"
                    + "  <argument name=\"formatUri\" type=\"string\">unknown</argument>\n"
                    + "  <argument name=\"dsContent\" type=\"stream\">PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPG5zZGxfZGM6bnNkbF9kYyBz\n"
                    + "Y2hlbWFWZXJzaW9uPSIxLjAyLjAwMCIKICB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2Vs\n"
                    + "ZW1lbnRzLzEuMS8iCiAgeG1sbnM6ZGN0PSJodHRwOi8vcHVybC5vcmcvZGMvdGVybXMvIgogIHht\n"
                    + "bG5zOm5zZGxfZGM9Imh0dHA6Ly9ucy5uc2RsLm9yZy9uc2RsX2RjX3YxLjAyLyIKICB4bWxuczp4\n"
                    + "c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6c2NoZW1h\n"
                    + "TG9jYXRpb249Imh0dHA6Ly9ucy5uc2RsLm9yZy9uc2RsX2RjX3YxLjAyLyBodHRwOi8vbnMubnNk\n"
                    + "bC5vcmcvc2NoZW1hcy9uc2RsX2RjL25zZGxfZGNfdjEuMDIueHNkIj4KICA8ZGM6aWRlbnRpZmll\n"
                    + "ciB4c2k6dHlwZT0iZGN0OlVSSSI+aHR0cDovL3NlcmMuY2FybGV0b24uZWR1L2ludHJvZ2VvL3Jv\n"
                    + "bGVwbGF5aW5nL2V4YW1wbGVzL2dsb2J3YXJtLmh0bWw8L2RjOmlkZW50aWZpZXI+CiAgPGRjOnR5\n"
                    + "cGU+Q2FsY3VsYXRpb24gb3IgQ29udmVyc2lvbiBUb29sPC9kYzp0eXBlPgogIDxkYzp0eXBlPlNj\n"
                    + "aWVudGlmaWMgVmlzdWFsaXphdGlvbjwvZGM6dHlwZT4KICA8ZGM6dHlwZSB4c2k6dHlwZT0iZGN0\n"
                    + "OkRDTUlUeXBlIj5JbWFnZTwvZGM6dHlwZT4KICA8ZGM6dHlwZSB4c2k6dHlwZT0iZGN0OkRDTUlU\n"
                    + "eXBlIj5JbnRlcmFjdGl2ZVJlc291cmNlPC9kYzp0eXBlPgogIDxkYzp0eXBlIHhzaTp0eXBlPSJk\n"
                    + "Y3Q6RENNSVR5cGUiPlNvZnR3YXJlPC9kYzp0eXBlPgogIDxkYzp0eXBlIHhzaTp0eXBlPSJkY3Q6RENNSVR5cGUi\n"
                    + "PlRleHQ8L2RjOnR5cGU+CiAgPGRjOnR5cGU+TGVzc29uPC9kYzp0eXBlPgogIDxkYzp0eXBlPkNv\n"
                    + "dXJzZTwvZGM6dHlwZT4KICA8ZGM6dHlwZT5Qcm9qZWN0PC9kYzp0eXBlPgogIDxkYzp0eXBlPlJl\n"
                    + "ZmVyZW5jZTwvZGM6dHlwZT4KICA8ZGM6dHlwZT5JbGx1c3RyYXRpb248L2RjOnR5cGU+CiAgPGRj\n"
                    + "OnR5cGU+TWFwPC9kYzp0eXBlPgogIDxkYzp0eXBlPlJlbW90ZWx5IFNlbnNlZCBJbWFnZXJ5PC9k\n"
                    + "Yzp0eXBlPgogIDxkYzp0eXBlPlNpbXVsYXRpb248L2RjOnR5cGU+CiAgPGRjOmZvcm1hdCB4c2k6\n"
                    + "dHlwZT0iZGN0OklNVCI+dGV4dC9odG1sPC9kYzpmb3JtYXQ+CiAgPGRjOmZvcm1hdD5BZG9iZSBB\n"
                    + "Y3JvYmF0IHJlYWRlcjwvZGM6Zm9ybWF0PgogIDxkYzpmb3JtYXQgeHNpOnR5cGU9ImRjdDpJTVQi\n"
                    + "PnZpZGVvL3F1aWNrdGltZTwvZGM6Zm9ybWF0PgogIDxkYzpmb3JtYXQ+TWljcm9zb2Z0IFdpbmRv\n"
                    + "d3M8L2RjOmZvcm1hdD4KICA8ZGM6Zm9ybWF0Pk1hY2ludG9zaDwvZGM6Zm9ybWF0PgogIDxkYzps\n"
                    + "YW5ndWFnZSB4c2k6dHlwZT0iZGN0OlJGQzMwNjYiPmVuPC9kYzpsYW5ndWFnZT4KICA8ZGM6ZGF0\n"
                    + "ZSB4c2k6dHlwZT0iZGN0OlczQ0RURiI+MjAwMS0wMS0wMTwvZGM6ZGF0ZT4KICA8ZGM6dGl0bGU+\n"
                    + "VGhlIFdvcmxkIFdhdGNoZXIgUHJvamVjdDogVGhlIEdsb2JhbCBXYXJtaW5nIFByb2plY3Q8L2Rj\n"
                    + "OnRpdGxlPgogIDxkYzpzdWJqZWN0PkNsaW1hdG9sb2d5PC9kYzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0PkVudmly\n"
                    + "b25tZW50YWwgc2NpZW5jZTwvZGM6c3ViamVjdD4KICA8ZGM6c3ViamVjdD5DcnlvbG9neTwvZGM6\n"
                    + "c3ViamVjdD4KICA8ZGM6c3ViamVjdD5QaHlzaWNhbCBnZW9ncmFwaHk8L2RjOnN1YmplY3Q+CiAg\n"
                    + "PGRjOnN1YmplY3Q+QXRtb3NwaGVyaWMgc2NpZW5jZTwvZGM6c3ViamVjdD4KICA8ZGM6c3ViamVj\n"
                    + "dD5SZW1vdGUgU2Vuc2luZzwvZGM6c3ViamVjdD4KICA8ZGM6c3ViamVjdD5TeXN0ZW1zPC9kYzpz\n"
                    + "dWJqZWN0PgogIDxkYzpzdWJqZWN0PkhlYXQgJmFtcDsgRW5lcmd5PC9kYzpzdWJqZWN0PgogIDxk\n"
                    + "YzpzdWJqZWN0PkNsaW1hdGUgQ2hhbmdlPC9kYzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0PlNjaWVu\n"
                    + "dGlmaWMgVmlzdWFsaXphdGlvbjwvZGM6c3ViamVjdD4KICA8ZGM6c3ViamVjdD5pbWFnZSBwcm9j\n"
                    + "ZXNzaW5nPC9kYzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0PkF0bW9zcGhlcmU8L2RjOnN1YmplY3Q+\n"
                    + "CiAgPGRjOnN1YmplY3Q+R2xvYmFsIENsaW1hdGUgU3lzdGVtczwvZGM6c3ViamVjdD4KICA8ZGM6\n"
                    + "c3ViamVjdD5FbnZpcm9ubWVudGFsIFNjaWVuY2U8L2RjOnN1YmplY3Q+CiAgPGRjOnN1YmplY3Q+\n"
                    + "SHVtYW4gZ2VvZ3JhcGh5PC9kYzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0PlRvcG9ncmFwaHkvUGh5\n"
                    + "c2ljYWwgR2VvZ3JhcGh5PC9kYzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0PlBvbGljeSBpc3N1ZXM8\n"
                    + "L2RjOnN1YmplY3Q+CiAgPGRjOnN1YmplY3Q+Q29tcG9zaXRpb24gYW5kIENoZW1pc3RyeTwvZGM6c3ViamVjdD4K\n"
                    + "ICA8ZGM6c3ViamVjdD5BdG1vc3BoZXJpYyBEeW5hbWljczwvZGM6c3ViamVjdD4KICA8ZGM6c3Vi\n"
                    + "amVjdD5HbG9iYWwgV2FybWluZzwvZGM6c3ViamVjdD4KICA8ZGM6c3ViamVjdD5XZWF0aGVyPC9k\n"
                    + "YzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0PkFudGhyb3BvZ2VuaWMgQWN0aXZpdHk8L2RjOnN1Ympl\n"
                    + "Y3Q+CiAgPGRjOnN1YmplY3Q+U3lzdGVtcywgSW50ZXJhY3Rpb25zLCBGZWVkYmFjayBMb29wczwv\n"
                    + "ZGM6c3ViamVjdD4KICA8ZGM6c3ViamVjdCB4c2k6dHlwZT0ibnNkbF9kYzpHRU0iPlNjaWVuY2U8\n"
                    + "L2RjOnN1YmplY3Q+CiAgPGRjOnN1YmplY3QgeHNpOnR5cGU9Im5zZGxfZGM6R0VNIj5FYXJ0aCBz\n"
                    + "Y2llbmNlPC9kYzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0IHhzaTp0eXBlPSJuc2RsX2RjOkdFTSI+\n"
                    + "UGh5c2ljYWwgc2NpZW5jZXM8L2RjOnN1YmplY3Q+CiAgPGRjOnN1YmplY3QgeHNpOnR5cGU9Im5z\n"
                    + "ZGxfZGM6R0VNIj5NZXRlb3JvbG9neTwvZGM6c3ViamVjdD4KICA8ZGM6c3ViamVjdCB4c2k6dHlw\n"
                    + "ZT0ibnNkbF9kYzpHRU0iPkdlb2xvZ3k8L2RjOnN1YmplY3Q+CiAgPGRjOnN1YmplY3QgeHNpOnR5\n"
                    + "cGU9Im5zZGxfZGM6R0VNIj5HZW9ncmFwaHk8L2RjOnN1YmplY3Q+CiAgPGRjOnN1YmplY3QgeHNp\n"
                    + "OnR5cGU9Im5zZGxfZGM6R0VNIj5DaGVtaXN0cnk8L2RjOnN1YmplY3Q+CiAgPGRjOnN1YmplY3Qg\n"
                    + "eHNpOnR5cGU9Im5zZGxfZGM6R0VNIj5QaHlzaWNzPC9kYzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0IHhzaTp0eXBl\n"
                    + "PSJuc2RsX2RjOkdFTSI+QXN0cm9ub215PC9kYzpzdWJqZWN0PgogIDxkYzpzdWJqZWN0IHhzaTp0\n"
                    + "eXBlPSJuc2RsX2RjOkdFTSI+U3BhY2Ugc2NpZW5jZXM8L2RjOnN1YmplY3Q+CiAgPGRjOmRlc2Ny\n"
                    + "aXB0aW9uPkdsb2JhbCB3YXJtaW5nIGFuZCBpdHMgcG90ZW50aWFsIGltcGFjdCBwcm92aWRlIHRo\n"
                    + "ZSBjb250ZXh0IGZvciB0aGlzIHVuaXQsIGluIHdoaWNoIHN0dWRlbnRzIGxlYXJuIGFib3V0IHRo\n"
                    + "ZSBzY2llbnRpZmljIGZhY3RvcnMgY29udHJpYnV0aW5nIHRvIHRoZSBkZWJhdGUuIFN0dWRlbnRz\n"
                    + "IGFjdCBhcyBhZHZpc29ycyB0byB0aGUgaGVhZHMgb2Ygc3RhdGUgb2Ygc2V2ZXJhbCBuYXRpb25z\n"
                    + "IGFuZCBleHBsb3JlIHRoZSBpc3N1ZXMgYXMgdGhleSByZXNwb25kIHRvIHRoZSB2YXJpb3VzIHF1\n"
                    + "ZXN0aW9ucyBhbmQgY29uY2VybnMgb2YgdGhlc2UgbGVhZGVycy4gQWN0aXZpdGllcyBpbmNsdWRl\n"
                    + "IGEgY29tYmluYXRpb24gb2YgcGh5c2ljYWwgbGFicyBhbmQgaW52ZXN0aWdhdGlvbnMgdXNpbmcg\n"
                    + "V29ybGQgV2F0Y2hlciBzb2Z0d2FyZSwgYSBnZW9ncmFwaGljIGRhdGEgdmlzdWFsaXphdGlvbiB0\n"
                    + "b29sIGRldmVsb3BlZCBieSBOb3J0aHdlc3Rlcm4gVW5pdmVyc2l0eS48L2RjOmRlc2NyaXB0aW9u\n"
                    + "PgogIDxkYzpyaWdodHM+VGhpcyBwcm9kdWN0IGlzIGZyZWUgYW5kIGNsZWFyIGZvciBnZW5lcmFs\n"
                    + "IHVzZS48L2RjOnJpZ2h0cz4KICA8ZGN0OmVkdWNhdGlvbkxldmVsIHhzaTp0eXBlPSJuc2RsX2RjOk5TRExFZExl\n"
                    + "dmVsIj5NaWRkbGUgU2Nob29sPC9kY3Q6ZWR1Y2F0aW9uTGV2ZWw+CiAgPGRjdDplZHVjYXRpb25M\n"
                    + "ZXZlbCB4c2k6dHlwZT0ibnNkbF9kYzpOU0RMRWRMZXZlbCI+SGlnaCBTY2hvb2w8L2RjdDplZHVj\n"
                    + "YXRpb25MZXZlbD4KPC9uc2RsX2RjOm5zZGxfZGM+Cgo=</argument>\n"
                    + "  <argument name=\"dsState\" type=\"string\">A</argument>\n"
                    + "  <argument name=\"message\" type=\"string\">Modified by NSDL API</argument>\n"
                    + "  <argument name=\"force\" type=\"boolean\">true</argument>\n"
                    + "</JournalEntry>";
}
