
package org.fcrepo.server.security.xacml.pdp.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-08-01T16:22:54.478+02:00
 * Generated source version: 2.4.0
 * 
 */

@WebFault(name = "evaluateBatchFault", targetNamespace = "http://pdp.xacml.melcoe/xsd")
public class EvaluateBatchFault_Exception extends Exception {
    public static final long serialVersionUID = 20110801162254L;
    
    private org.fcrepo.server.security.xacml.pdp.client.EvaluateBatchFault evaluateBatchFault;

    public EvaluateBatchFault_Exception() {
        super();
    }
    
    public EvaluateBatchFault_Exception(String message) {
        super(message);
    }
    
    public EvaluateBatchFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EvaluateBatchFault_Exception(String message, org.fcrepo.server.security.xacml.pdp.client.EvaluateBatchFault evaluateBatchFault) {
        super(message);
        this.evaluateBatchFault = evaluateBatchFault;
    }

    public EvaluateBatchFault_Exception(String message, org.fcrepo.server.security.xacml.pdp.client.EvaluateBatchFault evaluateBatchFault, Throwable cause) {
        super(message, cause);
        this.evaluateBatchFault = evaluateBatchFault;
    }

    public org.fcrepo.server.security.xacml.pdp.client.EvaluateBatchFault getFaultInfo() {
        return this.evaluateBatchFault;
    }
}
