
package org.fcrepo.server.security.xacml.pdp.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-08-01T16:22:54.423+02:00
 * Generated source version: 2.4.0
 * 
 */

@WebFault(name = "evaluateFault", targetNamespace = "http://pdp.xacml.melcoe/xsd")
public class EvaluateFault_Exception extends Exception {
    public static final long serialVersionUID = 20110801162254L;
    
    private org.fcrepo.server.security.xacml.pdp.client.EvaluateFault evaluateFault;

    public EvaluateFault_Exception() {
        super();
    }
    
    public EvaluateFault_Exception(String message) {
        super(message);
    }
    
    public EvaluateFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EvaluateFault_Exception(String message, org.fcrepo.server.security.xacml.pdp.client.EvaluateFault evaluateFault) {
        super(message);
        this.evaluateFault = evaluateFault;
    }

    public EvaluateFault_Exception(String message, org.fcrepo.server.security.xacml.pdp.client.EvaluateFault evaluateFault, Throwable cause) {
        super(message, cause);
        this.evaluateFault = evaluateFault;
    }

    public org.fcrepo.server.security.xacml.pdp.client.EvaluateFault getFaultInfo() {
        return this.evaluateFault;
    }
}
