
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.fcrepo.server.management2;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-07-12T12:46:46.704+02:00
 * Generated source version: 2.4.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "Fedora-API-M-MTOM-Service",
                      portName = "Fedora-API-M-MTOM-Port-SOAPHTTPS",
                      targetNamespace = "http://fedora-commons.org/2011/07/definitions/api/",
                      wsdlLocation = "file:/home/freon/workspace/fcrepo/fcrepo-common/../resources/wsdl/Fedora-API-M-MTOM.wsdl",
                      endpointInterface = "org.fcrepo.server.management2.FedoraAPIMMTOM")
                      
public class FedoraAPIMMTOMImpl1 implements FedoraAPIMMTOM {

    private static final Logger LOG = Logger.getLogger(FedoraAPIMMTOMImpl1.class.getName());

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#compareDatastreamChecksum(java.lang.String  pid ,)java.lang.String  dsID ,)java.lang.String  versionDate )*
     */
    public java.lang.String compareDatastreamChecksum(java.lang.String pid,java.lang.String dsID,java.lang.String versionDate) { 
        LOG.info("Executing operation compareDatastreamChecksum");
        System.out.println(pid);
        System.out.println(dsID);
        System.out.println(versionDate);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#export(java.lang.String  pid ,)java.lang.String  format ,)java.lang.String  context )*
     */
    public javax.activation.DataHandler export(java.lang.String pid,java.lang.String format,java.lang.String context) { 
        LOG.info("Executing operation export");
        System.out.println(pid);
        System.out.println(format);
        System.out.println(context);
        try {
            javax.activation.DataHandler _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#purgeRelationship(java.lang.String  pid ,)java.lang.String  relationship ,)java.lang.String  object ,)boolean  isLiteral ,)java.lang.String  datatype )*
     */
    public boolean purgeRelationship(java.lang.String pid,java.lang.String relationship,java.lang.String object,boolean isLiteral,java.lang.String datatype) { 
        LOG.info("Executing operation purgeRelationship");
        System.out.println(pid);
        System.out.println(relationship);
        System.out.println(object);
        System.out.println(isLiteral);
        System.out.println(datatype);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#purgeObject(java.lang.String  pid ,)java.lang.String  logMessage ,)boolean  force )*
     */
    public java.lang.String purgeObject(java.lang.String pid,java.lang.String logMessage,boolean force) { 
        LOG.info("Executing operation purgeObject");
        System.out.println(pid);
        System.out.println(logMessage);
        System.out.println(force);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#modifyDatastreamByValue(java.lang.String  pid ,)java.lang.String  dsID ,)org.fcrepo.server.types2.gen.ArrayOfString  altIDs ,)java.lang.String  dsLabel ,)java.lang.String  mimeType ,)java.lang.String  formatURI ,)javax.activation.DataHandler  dsContent ,)java.lang.String  checksumType ,)java.lang.String  checksum ,)java.lang.String  logMessage ,)boolean  force )*
     */
    public java.lang.String modifyDatastreamByValue(java.lang.String pid,java.lang.String dsID,org.fcrepo.server.types2.gen.ArrayOfString altIDs,java.lang.String dsLabel,java.lang.String mimeType,java.lang.String formatURI,javax.activation.DataHandler dsContent,java.lang.String checksumType,java.lang.String checksum,java.lang.String logMessage,boolean force) { 
        LOG.info("Executing operation modifyDatastreamByValue");
        System.out.println(pid);
        System.out.println(dsID);
        System.out.println(altIDs);
        System.out.println(dsLabel);
        System.out.println(mimeType);
        System.out.println(formatURI);
        System.out.println(dsContent);
        System.out.println(checksumType);
        System.out.println(checksum);
        System.out.println(logMessage);
        System.out.println(force);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#setDatastreamState(java.lang.String  pid ,)java.lang.String  dsID ,)java.lang.String  dsState ,)java.lang.String  logMessage )*
     */
    public java.lang.String setDatastreamState(java.lang.String pid,java.lang.String dsID,java.lang.String dsState,java.lang.String logMessage) { 
        LOG.info("Executing operation setDatastreamState");
        System.out.println(pid);
        System.out.println(dsID);
        System.out.println(dsState);
        System.out.println(logMessage);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#setDatastreamVersionable(java.lang.String  pid ,)java.lang.String  dsID ,)boolean  versionable ,)java.lang.String  logMessage )*
     */
    public java.lang.String setDatastreamVersionable(java.lang.String pid,java.lang.String dsID,boolean versionable,java.lang.String logMessage) { 
        LOG.info("Executing operation setDatastreamVersionable");
        System.out.println(pid);
        System.out.println(dsID);
        System.out.println(versionable);
        System.out.println(logMessage);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#addDatastream(java.lang.String  pid ,)java.lang.String  dsID ,)org.fcrepo.server.types2.gen.ArrayOfString  altIDs ,)java.lang.String  dsLabel ,)boolean  versionable ,)java.lang.String  mimeType ,)java.lang.String  formatURI ,)java.lang.String  dsLocation ,)java.lang.String  controlGroup ,)java.lang.String  dsState ,)java.lang.String  checksumType ,)java.lang.String  checksum ,)java.lang.String  logMessage )*
     */
    public java.lang.String addDatastream(java.lang.String pid,java.lang.String dsID,org.fcrepo.server.types2.gen.ArrayOfString altIDs,java.lang.String dsLabel,boolean versionable,java.lang.String mimeType,java.lang.String formatURI,java.lang.String dsLocation,java.lang.String controlGroup,java.lang.String dsState,java.lang.String checksumType,java.lang.String checksum,java.lang.String logMessage) { 
        LOG.info("Executing operation addDatastream");
        System.out.println(pid);
        System.out.println(dsID);
        System.out.println(altIDs);
        System.out.println(dsLabel);
        System.out.println(versionable);
        System.out.println(mimeType);
        System.out.println(formatURI);
        System.out.println(dsLocation);
        System.out.println(controlGroup);
        System.out.println(dsState);
        System.out.println(checksumType);
        System.out.println(checksum);
        System.out.println(logMessage);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#validate(java.lang.String  pid ,)java.lang.String  asOfDateTime )*
     */
    public org.fcrepo.server.types2.gen.Validation validate(java.lang.String pid,java.lang.String asOfDateTime) { 
        LOG.info("Executing operation validate");
        System.out.println(pid);
        System.out.println(asOfDateTime);
        try {
            org.fcrepo.server.types2.gen.Validation _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#modifyDatastreamByReference(java.lang.String  pid ,)java.lang.String  dsID ,)org.fcrepo.server.types2.gen.ArrayOfString  altIDs ,)java.lang.String  dsLabel ,)java.lang.String  mimeType ,)java.lang.String  formatURI ,)java.lang.String  dsLocation ,)java.lang.String  checksumType ,)java.lang.String  checksum ,)java.lang.String  logMessage ,)boolean  force )*
     */
    public java.lang.String modifyDatastreamByReference(java.lang.String pid,java.lang.String dsID,org.fcrepo.server.types2.gen.ArrayOfString altIDs,java.lang.String dsLabel,java.lang.String mimeType,java.lang.String formatURI,java.lang.String dsLocation,java.lang.String checksumType,java.lang.String checksum,java.lang.String logMessage,boolean force) { 
        LOG.info("Executing operation modifyDatastreamByReference");
        System.out.println(pid);
        System.out.println(dsID);
        System.out.println(altIDs);
        System.out.println(dsLabel);
        System.out.println(mimeType);
        System.out.println(formatURI);
        System.out.println(dsLocation);
        System.out.println(checksumType);
        System.out.println(checksum);
        System.out.println(logMessage);
        System.out.println(force);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#addRelationship(java.lang.String  pid ,)java.lang.String  relationship ,)java.lang.String  object ,)boolean  isLiteral ,)java.lang.String  datatype )*
     */
    public boolean addRelationship(java.lang.String pid,java.lang.String relationship,java.lang.String object,boolean isLiteral,java.lang.String datatype) { 
        LOG.info("Executing operation addRelationship");
        System.out.println(pid);
        System.out.println(relationship);
        System.out.println(object);
        System.out.println(isLiteral);
        System.out.println(datatype);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#getNextPID(java.math.BigInteger  numPIDs ,)java.lang.String  pidNamespace )*
     */
    public java.util.List<java.lang.String> getNextPID(java.math.BigInteger numPIDs,java.lang.String pidNamespace) { 
        LOG.info("Executing operation getNextPID");
        System.out.println(numPIDs);
        System.out.println(pidNamespace);
        try {
            java.util.List<java.lang.String> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#getRelationships(java.lang.String  pid ,)java.lang.String  relationship )*
     */
    public java.util.List<org.fcrepo.server.types2.gen.RelationshipTuple> getRelationships(java.lang.String pid,java.lang.String relationship) { 
        LOG.info("Executing operation getRelationships");
        System.out.println(pid);
        System.out.println(relationship);
        try {
            java.util.List<org.fcrepo.server.types2.gen.RelationshipTuple> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#getObjectXML(java.lang.String  pid )*
     */
    public javax.activation.DataHandler getObjectXML(java.lang.String pid) { 
        LOG.info("Executing operation getObjectXML");
        System.out.println(pid);
        try {
            javax.activation.DataHandler _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#modifyObject(java.lang.String  pid ,)java.lang.String  state ,)java.lang.String  label ,)java.lang.String  ownerId ,)java.lang.String  logMessage )*
     */
    public java.lang.String modifyObject(java.lang.String pid,java.lang.String state,java.lang.String label,java.lang.String ownerId,java.lang.String logMessage) { 
        LOG.info("Executing operation modifyObject");
        System.out.println(pid);
        System.out.println(state);
        System.out.println(label);
        System.out.println(ownerId);
        System.out.println(logMessage);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#ingest(javax.activation.DataHandler  objectXML ,)java.lang.String  format ,)java.lang.String  logMessage )*
     */
    public java.lang.String ingest(javax.activation.DataHandler objectXML,java.lang.String format,java.lang.String logMessage) { 
        LOG.info("Executing operation ingest");
        System.out.println(objectXML);
        System.out.println(format);
        System.out.println(logMessage);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#purgeDatastream(java.lang.String  pid ,)java.lang.String  dsID ,)java.lang.String  startDT ,)java.lang.String  endDT ,)java.lang.String  logMessage ,)boolean  force )*
     */
    public java.util.List<java.lang.String> purgeDatastream(java.lang.String pid,java.lang.String dsID,java.lang.String startDT,java.lang.String endDT,java.lang.String logMessage,boolean force) { 
        LOG.info("Executing operation purgeDatastream");
        System.out.println(pid);
        System.out.println(dsID);
        System.out.println(startDT);
        System.out.println(endDT);
        System.out.println(logMessage);
        System.out.println(force);
        try {
            java.util.List<java.lang.String> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#getDatastreamHistory(java.lang.String  pid ,)java.lang.String  dsID )*
     */
    public java.util.List<org.fcrepo.server.types2.gen.Datastream> getDatastreamHistory(java.lang.String pid,java.lang.String dsID) { 
        LOG.info("Executing operation getDatastreamHistory");
        System.out.println(pid);
        System.out.println(dsID);
        try {
            java.util.List<org.fcrepo.server.types2.gen.Datastream> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#getDatastreams(java.lang.String  pid ,)java.lang.String  asOfDateTime ,)java.lang.String  dsState )*
     */
    public java.util.List<org.fcrepo.server.types2.gen.Datastream> getDatastreams(java.lang.String pid,java.lang.String asOfDateTime,java.lang.String dsState) { 
        LOG.info("Executing operation getDatastreams");
        System.out.println(pid);
        System.out.println(asOfDateTime);
        System.out.println(dsState);
        try {
            java.util.List<org.fcrepo.server.types2.gen.Datastream> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.fcrepo.server.management2.FedoraAPIMMTOM#getDatastream(java.lang.String  pid ,)java.lang.String  dsID ,)java.lang.String  asOfDateTime )*
     */
    public org.fcrepo.server.types2.gen.Datastream getDatastream(java.lang.String pid,java.lang.String dsID,java.lang.String asOfDateTime) { 
        LOG.info("Executing operation getDatastream");
        System.out.println(pid);
        System.out.println(dsID);
        System.out.println(asOfDateTime);
        try {
            org.fcrepo.server.types2.gen.Datastream _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
